# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb
      REPORTING_RERUN_CONDITION: "<< pipeline.parameters.reporting-rerun-context >>"
    steps:
      - run: echo "Image tag used was ${REPORTING_RERUN_CONDITION}"
      - checkout
      - run: mvn clean test
  hoho:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb
      REPORTING_RERUN_CONDITION: "<< pipeline.parameters.reporting-rerun-context >>"
    steps:
      - run: echo "Image tag used was ${REPORTING_RERUN_CONDITION}"
      - checkout
      - run: mvn clean test

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
      - hoho

parameters:
  reporting-rerun-context:
    default: ""
    type: string


